question_data = [{"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                  "question": "Han Solo&#039;s co-pilot and best friend, &quot;Chewbacca&quot;, is an Ewok.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                  "question": "The word &quot;Inception&quot; came from the 2010 blockbuster hit &quot;Inception&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                  "question": "In the original script of &quot;The Matrix&quot;, the machines used humans as additional computing power instead of batteries.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                  "question": "Shaquille O&#039;Neal appeared in the 1997 film &quot;Space Jam&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                  "question": "Ewan McGregor did not know the name of the second prequel film of Star Wars during and after filming.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                  "question": "In Alfred Hitchcock&#039;s film &#039;Psycho&#039; it is said he used chocolate syrup to simulate the blood in the famous shower scene from ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                  "question": "In the original Star Wars trilogy, David Prowse was the actor who physically portrayed Darth Vader.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                  "question": "George Lucas directed the entire original Star Wars trilogy.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                  "question": "&quot;Minions&quot; was released on the June 10th, 2015.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                  "question": "&quot;Foodfight!&quot; earned less than $80,000 at box office.",
                  "correct_answer": "True", "incorrect_answers": ["False"]}]
